import type { AtRiskSession } from "./types";

export const mockSessions: AtRiskSession[] = [
  {
    session_id: "sess_001",
    customer_id: "cust_8821",
    customer_name: "Priya Sharma",
    friction_flags: [
      { type: "cart_abandoned", confidence: 0.93, signal: "Added 3 items to cart, no purchase in 52 min" },
      { type: "hesitation", confidence: 0.71, signal: "Visited product page 4 times in 30 min" },
    ],
    product: { name: "Sony WH-1000XM5 Headphones", category: "Electronics", price: 349 },
    cart_value: 697,
    feedback_text: "Not sure if the noise cancellation is worth the price.",
    likely_cause: "Customer is showing strong purchase intent but hesitating due to price uncertainty. Multiple product page revisits suggest comparison shopping behavior.",
    recommended_action: "offer_discount",
    risk_tier: "high",
    risk_score: 0.91,
    timestamp: "2026-08-19T07:22:00Z",
  },
  {
    session_id: "sess_002",
    customer_id: "cust_4402",
    customer_name: "Rahul Menon",
    friction_flags: [
      { type: "payment_friction", confidence: 0.88, signal: "Payment page reloaded 3 times, card declined once" },
    ],
    product: { name: "Nike Air Max 270", category: "Footwear", price: 150 },
    cart_value: 150,
    feedback_text: null,
    likely_cause: "Customer encountered a payment processing issue. A single card decline followed by multiple page reloads strongly suggests technical friction rather than intent to abandon.",
    recommended_action: "route_to_agent",
    risk_tier: "high",
    risk_score: 0.87,
    timestamp: "2026-08-19T07:14:00Z",
  },
  {
    session_id: "sess_003",
    customer_id: "cust_7731",
    customer_name: "Ananya Krishnan",
    friction_flags: [
      { type: "delivery_concern", confidence: 0.79, signal: "Opened shipping FAQ 5 times, filtered by delivery date" },
      { type: "hesitation", confidence: 0.64, signal: "Idle on checkout page for 18 min" },
    ],
    product: { name: "Instant Pot Duo 7-in-1", category: "Kitchen", price: 99 },
    cart_value: 99,
    feedback_text: "Need it before my sister's wedding on the 25th.",
    likely_cause: "Customer has a time-sensitive delivery requirement. Repeated FAQ visits suggest uncertainty about whether the product will arrive in time for a specific event.",
    recommended_action: "send_faq_link",
    risk_tier: "low",
    risk_score: 0.72,
    timestamp: "2026-08-19T06:58:00Z",
  },
  {
    session_id: "sess_004",
    customer_id: "cust_2210",
    customer_name: "Vikram Nair",
    friction_flags: [
      { type: "cart_abandoned", confidence: 0.95, signal: "Cart inactive for 2 hours after reaching checkout" },
    ],
    product: { name: 'Samsung 65" QLED 4K TV', category: "Electronics", price: 1199 },
    cart_value: 1199,
    feedback_text: null,
    likely_cause: "High-value cart abandoned at the final checkout stage. This pattern often indicates sticker shock or a need for spousal approval before committing to a large purchase.",
    recommended_action: "send_reminder_email",
    risk_tier: "high",
    risk_score: 0.96,
    timestamp: "2026-08-19T05:30:00Z",
  },
  {
    session_id: "sess_005",
    customer_id: "cust_9981",
    customer_name: "Divya Patel",
    friction_flags: [
      { type: "hesitation", confidence: 0.58, signal: "Read 12 customer reviews, session lasted 47 min" },
    ],
    product: { name: "Dyson V15 Detect Vacuum", category: "Home Appliances", price: 749 },
    cart_value: 749,
    feedback_text: "Mixed reviews about battery life are concerning.",
    likely_cause: "Customer is in deep research mode, spending significant time reading reviews. The specific concern about battery life suggests one negative feature is blocking an otherwise positive evaluation.",
    recommended_action: "send_faq_link",
    risk_tier: "low",
    risk_score: 0.61,
    timestamp: "2026-08-19T07:01:00Z",
  },
  {
    session_id: "sess_006",
    customer_id: "cust_3345",
    customer_name: "Arjun Reddy",
    friction_flags: [
      { type: "payment_friction", confidence: 0.91, signal: "Switched payment methods 3 times on checkout" },
      { type: "cart_abandoned", confidence: 0.82, signal: "Left cart page open, no interaction for 35 min" },
    ],
    product: { name: "Apple AirPods Pro (2nd Gen)", category: "Electronics", price: 249 },
    cart_value: 498,
    feedback_text: null,
    likely_cause: "Customer is experiencing friction at payment — cycling through multiple methods indicates preferred payment option may be unavailable or failing. Secondary cart abandonment signal compounds urgency.",
    recommended_action: "route_to_agent",
    risk_tier: "high",
    risk_score: 0.89,
    timestamp: "2026-08-19T06:45:00Z",
  },
  {
    session_id: "sess_007",
    customer_id: "cust_5567",
    customer_name: "Meera Iyer",
    friction_flags: [
      { type: "delivery_concern", confidence: 0.85, signal: "Searched 'return policy' and 'international shipping' 3 times" },
    ],
    product: { name: "Levi's 501 Original Jeans", category: "Apparel", price: 69.95 },
    cart_value: 139.90,
    feedback_text: "Ordering as a gift for someone abroad.",
    likely_cause: "Customer intends to ship internationally and is researching whether the store supports this. Uncertainty about return policies for gift purchases adds an additional barrier.",
    recommended_action: "send_faq_link",
    risk_tier: "low",
    risk_score: 0.68,
    timestamp: "2026-08-19T07:08:00Z",
  },
  {
    session_id: "sess_008",
    customer_id: "cust_1123",
    customer_name: "Karthik Suresh",
    friction_flags: [
      { type: "hesitation", confidence: 0.77, signal: "Added to cart, removed, re-added product twice" },
      { type: "delivery_concern", confidence: 0.69, signal: "Filtered delivery options by 'Express' 4 times" },
      { type: "cart_abandoned", confidence: 0.62, signal: "No activity for 28 min after viewing cart" },
    ],
    product: { name: "MacBook Air M3 13\"", category: "Computers", price: 1099 },
    cart_value: 1099,
    feedback_text: null,
    likely_cause: "Customer is demonstrating classic decision fatigue with a high-value purchase. The add/remove cycle combined with delivery speed concerns suggests both product fit uncertainty and timeline pressure.",
    recommended_action: "offer_discount",
    risk_tier: "high",
    risk_score: 0.94,
    timestamp: "2026-08-19T06:10:00Z",
  },
  {
    session_id: "sess_009",
    customer_id: "cust_6678",
    customer_name: "Sneha Bose",
    friction_flags: [
      { type: "cart_abandoned", confidence: 0.76, signal: "Added to cart, no purchase in 1.5 hours" },
    ],
    product: { name: "Kindle Paperwhite 11th Gen", category: "Electronics", price: 139.99 },
    cart_value: 139.99,
    feedback_text: "Waiting to see if this goes on sale.",
    likely_cause: "Customer has clear purchase intent but is waiting for a price reduction. The feedback text explicitly confirms a price-sensitive hold pattern rather than disinterest in the product.",
    recommended_action: "offer_discount",
    risk_tier: "low",
    risk_score: 0.74,
    timestamp: "2026-08-19T05:55:00Z",
  },
  {
    session_id: "sess_010",
    customer_id: "cust_8890",
    customer_name: "Rohit Joshi",
    friction_flags: [
      { type: "payment_friction", confidence: 0.94, signal: "PayPal checkout threw an error twice" },
      { type: "hesitation", confidence: 0.56, signal: "Spent 8 min on the returns/warranty page" },
    ],
    product: { name: "LEGO Technic Bugatti Chiron", category: "Toys & Hobbies", price: 449.99 },
    cart_value: 449.99,
    feedback_text: null,
    likely_cause: "PayPal integration errors are causing direct checkout failure. The secondary hesitation signal around returns suggests concerns about product quality for the price point.",
    recommended_action: "route_to_agent",
    risk_tier: "high",
    risk_score: 0.92,
    timestamp: "2026-08-19T07:18:00Z",
  },
  {
    session_id: "sess_011",
    customer_id: "cust_3312",
    customer_name: "Lakshmi Venkat",
    friction_flags: [
      { type: "delivery_concern", confidence: 0.88, signal: "Pincode entered and re-entered 3 times on checkout" },
    ],
    product: { name: "Prestige Iris 750W Mixer Grinder", category: "Kitchen", price: 79.99 },
    cart_value: 79.99,
    feedback_text: "Not sure if they deliver to my area.",
    likely_cause: "Customer is uncertain whether delivery is available to their location. Pincode re-entry behavior is a strong signal of serviceability anxiety blocking purchase completion.",
    recommended_action: "send_faq_link",
    risk_tier: "low",
    risk_score: 0.55,
    timestamp: "2026-08-19T06:30:00Z",
  },
  {
    session_id: "sess_012",
    customer_id: "cust_7723",
    customer_name: "Aditya Kumar",
    friction_flags: [
      { type: "hesitation", confidence: 0.83, signal: "Browsed 6 similar products before settling on one" },
      { type: "cart_abandoned", confidence: 0.78, signal: "Cart open for 90 min without proceeding to payment" },
    ],
    product: { name: "Fitbit Charge 6", category: "Wearables", price: 159.95 },
    cart_value: 319.90,
    feedback_text: "Can't decide between this and the Garmin.",
    likely_cause: "Customer is actively comparison shopping between fitness tracker brands. The feedback confirms a classic two-product dilemma — targeted comparison content or a small incentive could tip the decision.",
    recommended_action: "send_reminder_email",
    risk_tier: "low",
    risk_score: 0.76,
    timestamp: "2026-08-19T05:45:00Z",
  },
  {
    session_id: "sess_013",
    customer_id: "cust_5541",
    customer_name: "Pooja Nambiar",
    friction_flags: [
      { type: "payment_friction", confidence: 0.97, signal: "Transaction declined 4 times, 2 different cards" },
      { type: "cart_abandoned", confidence: 0.91, signal: "Abandoned after final payment decline" },
    ],
    product: { name: "Sabyasachi Designer Saree", category: "Apparel", price: 890 },
    cart_value: 890,
    feedback_text: "This was meant to be my anniversary gift to myself.",
    likely_cause: "Critical payment gateway failure is preventing an emotionally motivated purchase. Multiple card declines across different cards suggest a platform-side issue. Immediate agent intervention required.",
    recommended_action: "route_to_agent",
    risk_tier: "high",
    risk_score: 0.97,
    timestamp: "2026-08-19T07:25:00Z",
  },
  {
    session_id: "sess_014",
    customer_id: "cust_2298",
    customer_name: "Sanjay Mehta",
    friction_flags: [
      { type: "hesitation", confidence: 0.61, signal: "Zoomed into product images 15 times" },
      { type: "delivery_concern", confidence: 0.73, signal: "Checked estimated delivery date 7 times" },
    ],
    product: { name: "Fossil Gen 6 Smartwatch", category: "Wearables", price: 299 },
    cart_value: 299,
    feedback_text: null,
    likely_cause: "Customer is scrutinizing product appearance and delivery timing. The high image zoom frequency indicates concern about physical product quality that static images aren't resolving.",
    recommended_action: "send_reminder_email",
    risk_tier: "low",
    risk_score: 0.63,
    timestamp: "2026-08-19T06:20:00Z",
  },
  {
    session_id: "sess_015",
    customer_id: "cust_9904",
    customer_name: "Nisha Kapoor",
    friction_flags: [
      { type: "cart_abandoned", confidence: 0.86, signal: "Checkout initiated but browser closed mid-flow" },
      { type: "payment_friction", confidence: 0.74, signal: "Address validation failed once during checkout" },
      { type: "delivery_concern", confidence: 0.67, signal: "Selected and changed delivery slot 4 times" },
    ],
    product: { name: "Philips Air Fryer XXL", category: "Kitchen", price: 299.95 },
    cart_value: 599.90,
    feedback_text: null,
    likely_cause: "Customer experienced a compounding set of checkout friction points — address validation failure, delivery indecision, and ultimately a browser session loss. Recovery requires re-engagement with a simplified checkout path.",
    recommended_action: "send_reminder_email",
    risk_tier: "high",
    risk_score: 0.85,
    timestamp: "2026-08-19T07:05:00Z",
  },
];
